### ISSUE TITLE
suggestion on installation instruction

### ISSUE THREAD

**Issue by GattoJohnny** [balassy/MMM-Futar#12]
> To use this module follow these steps:
>     Clone this repository to the modules folder of your MagicMirror:
> git clone https://github.com/balassy/MMM-Futar.git
>     Install third-party dependencies:
> npm install

You may want to add "cd MMM-Futar" in the documentation between cloning and _npm install_ for noobs like me. Yep, it did happen! 🤣

**Comment by balassy** [comment]
Thanks for the suggestion, I added the missing step in https://github.com/balassy/MMM-Futar/commit/cd895060bd50049f1cd92a6c442a118a3ab8ed3e.
