### ISSUE TITLE
"X perc múlva" helyett csak "X perc"

### ISSUE THREAD

**Issue by zoldev** [balassy/MMM-Futar#21]
Tisztelt György!

Kérdésem az lenne, hogy a járat érkezési idejének kijelzését le lehetne rövídíteni?
Pl.: "12 perc múlva" helyett csak annyit írna ki a modul hogy "12 perc".

Csak amiatt lenne hasznos, mert így jelentősen csökkenthető lenne a modul szélessége. Sok esetben helytakarékosabb lenne.

Köszönöm válaszod!
Üdv,
Zoltán

**Comment by balassy** [comment]
Kedves Zoltán!

Igen, ezen én is gondolkodtam korábban, két oka van, amiért mégis így maradt:

1. Technikailag nehezen megoldható. A szöveget nem a Futár modul állítja elő, hanem a MagicMirror által használt és javasolt [Moment.js](https://momentjs.com/) library, tehát nem tudjuk egyszerűen megváltoztatni a szöveget. További szempont, hogy így egységes a megjelenítés más modulokkal, illetve hogy így a modul kódja nem tartalmaz nyelv specifikus kódot, azért teljes mértékben a MagicMirror illetve a Moment.js a felelős.

2. A Futár modulnak sokszor van szüksége nagy helyre, például amikor "Nem indul a következő 50 percben" szöveget, vagy a menetrendet érintő figyelmeztetéseket jelenít meg. Ezekhez képest az egyetlen "múlva" szó elhagyása csekély nyereségnek tűnik, hiszen érdemes a modult olyan helyre tenni a MagicMirroron, hogy hosszabb szövegeket is meg tudjon jeleníteni, amikor szükség van rá.

Mit gondolsz?

Üdv:
Balássy György

**Comment by balassy** [comment]
Lezárom, mert nem érkezett válasz.
