### ISSUE TITLE
Futár seems to be gone

### ISSUE THREAD

**Issue by GattoJohnny** [balassy/MMM-Futar#24]
My module has stopped working. This may be the reason: https://bkk.hu/hirek/2022/02/viszlat-futar-hello-budapestgo.7308/
Is there a chance that you make this awesome module work with the new BudapestGO?

**Comment by balassy** [comment]
Hello @GattoJohnny,

The module is working well on my MagicMirror and since it is using the same API as https://futar.bkk.hu which is still available I think it is highly unlikely that your issue is related to the Budapest GO announcement. Could you please attach your configuration section so I can try to reproduce your issue? 

Thanks.

**Comment by GattoJohnny** [comment]
Hello and thanks for the prompt reply. Something else is going on. I took a look at the PM2 logs and found that it was an authorization issue. As per the logs:
"_MMM-Futar Node helper: Failed to load data in the background. Error: Error: certificate has expired. Response: undefined_"

I use the default value for updateInterval: 60000, // 1 minute in milliseconds.

**Comment by GattoJohnny** [comment]
Okay, this screenshot was made by 
- replacing my fuzzy config with a simple default MM config, 
- getting rid of everything but the 'newsfeed' module, 
- adding your default MMM-Futar config 
- plus a 'SAMPLE CONFIG FILE' header so that you can see where the schedule should appear.

Pm2 logs show the same certi error message that I've been receiving for about two weeks.

So my config goes like this

>     {
>       module: 'MMM-Futar',
>       position: 'top_left',
>       header: "SAMPLE CONFIG FILE",
>       config: {
>         stopId: 'BKK_F02285',
>         routeId: 'BKK_1020',
>         minutesAfter: 50,
>         hideStopTimesInNextMinutes: 0,
>         updateInterval: 60000, // 1 minute in milliseconds
>         showHead: true, // true | false
>         showSymbolInHead: true, // true | false
>         showSymbolInStopTime: false, // true | false
>         showRouteNameInStopTime: false, // true | false
>         maxNumberOfItems: 3,
>         align: 'left', // 'left' | 'right'
>         fade: true,
>         fadePoint: 0.25,
>         coloredSymbolInHead: true, // true | false
>         coloredTextInHead: true, // true | false
>         coloredSymbolInStopTime: true, // true | false
>         coloredRouteNameInStopTime: true, // true | false
>         symbolColors: {
>           tram: '#ffcf42', // yellow-ish
>           bus: '#1a9fed', // blue-ish
>           subway: '#b3090c', // red-ish
>           trolleybus: '#931517', // dark red-ish
>           rail: '#5cbc82', // green-ish
>           ferry: '#1a52ed' // dark-blue-ish
>         },
>         alerts: {
>           showHeaderInStopTime: true, // true | false
>           showSymbolInStopTime: true, // true | false
>           color: '#ffcf42', // 'auto' or any CSS color
>           language: 'en' // 'en' or 'hu' supported only by the Futár API
>         }
>       }
>     },

![MMM-Futar-20220218-01](https://user-images.githubusercontent.com/47010649/154712841-badc04fe-ae34-438b-a15a-e8fdef4ec06a.jpg)

**Comment by balassy** [comment]
That's really interesting. Or rather weird. The module calls to `https://futar.bkk.hu` which has a certificate that expires on 2022-03-10. I checked my pm2 logs as well and I don't see these errors on my Pi, but I could reproduce it locally. 

I've found a thread with the same error, and the solution is to upgrade MagicMirror to 2.17.1 or later. Could you please try that?

Related: https://github.com/MichMich/MagicMirror/issues/2671

**Comment by GattoJohnny** [comment]
It was a snowball thrown on the top of a hill causing a massive avalanche. I had to reinstall everything from scratch because the usual update procedure did not work out for me. But after a couple of hours of pain and detours like the electron-rebuild issue and etc. I could finally got it working.

So thank you for the hint, it did the trick.
