### ISSUE TITLE
tobb jarat ugyanaz a StopId

### ISSUE THREAD

**Issue by unixgirl** [balassy/MMM-Futar#26]
Sziasztok, olyan kerdesem van ami inkabb beallitasi gond. Elolvastam ugyan a README-t de nem vilagos es nem is mukodik ugy a modul ahogy kellene. 

" If you would like to see the departure times of more stops and routes on your mirror, add this module multiple times."

Az irast ertem de ezt hogyan kellene kivitelezni? 

Masoljam be a modult a  MagicMirror/modules mappaba? mert egy es ugyanaz neven nem lehet merthogy mar letezik a modul.

Vegulis amit szeretnek elerni, hogy az alabbi  vonalakat jelenitse meg.
H6 os Hev kozvagohid - rackeve valamint rackeve - kozvagohid
38 as busz szigetszentmiklos - budapest
238 as busz szigetszentmiklos - budapest,

Tudnatok egy kis iranyvonalat mutatni hogy ezt mikeppen tudom megoldani?

**Comment by balassy** [comment]
Szia @unixgirl!
Nem kell bemásolni a `modules` mappába többször a modult. A trükk, hogy a `config.js` fájl `modules` szekciójába viszont felveheted többször. Valahogy így:
```
var config = {
    // ...
    modules: [
        {
            module: "MMM-Futar",
            position: "top_left",
            header: 'Közvágóhíd -> Ráckeve',
            config: {
                stopId: 'BKK_009628',  // Közvágóhíd
                routeId: 'BKK_H6,
            }
        },
        {
            module: "MMM-Futar",
            position: "top_left",
            header: 'Ráckeve -> Közvágóhíd',
            config: {
                stopId: 'BKK_007947',  // Ráckeve
                routeId: 'BKK_H6',
            }
        },
    ]
};
```

Remélem ez így működni fog! :)

**Comment by unixgirl** [comment]
Wow ok ezt megprobalom igy akkor, mert a forumba teljesen mas megoldast javasoltak. Szerdan erek haza Hollandbol es akkor nekifutok, jelzek majd hogy mi lett. Koszonom a segitseget!

**Comment by unixgirl** [comment]
Szia, nem igazan tudom mukodesre birni :)  valami syntax hibaval nem indul el a tukor es hivatkozik a config ks file-ra.
Ket napja probalok rajonni a de nem mukodik. Ami hiobakat ir hogy hanyas sorban ott altalban a kapcsos zarojelekkel van gondja de ha kitorolom akkor lesz mashol hiba. Bemasoltam a config file-t a pastebin-re ha esetleg idod engedi raneznel kerlek?
https://pastebin.com/rejiHeFt

**Comment by unixgirl** [comment]
Az alabbi beallitassal csak fekete kepernyot kapok, az elozo pastebines config nal viszont megjelenik a felhivas miszerint a config file-t piszkaljam.
https://pastebin.com/bwrTtisP

**Comment by unixgirl** [comment]
Szia, a magicmirror.builders forumon meglett a megoldas, szerintem zard nyugodtan. Koszi  a projectbe fektett idodet!

**Comment by balassy** [comment]
Örülök, hogy megoldódott. Mi volt a megoldás? Lehet, hogy ugyanaz, amit az Issue #27 -ben jeleztek itt nekem a héten?

**Comment by unixgirl** [comment]
Szia, most jottem vissza gorogbol bocs a kesei valasz miatt. Nem, az a problema nem all fent amit neked jeleztek, legalabbis  a modulod mukodese kapcsan. A megoldas pedig az volt hogy  a config js bol ki kell venni az alabbi reszt.
https://pastebin.com/rMDtGZnM

ilyennek kell legyen a config js

 {
            module: "MMM-Futar",
            position: "top_left",
            header: 'Közvágóhíd -> Ráckeve',
            config: {
                stopId: 'BKK_009628',  // Közvágóhíd
                routeId: 'BKK_H6,
            }
        },
        {
            module: "MMM-Futar",
            position: "top_left",
            header: 'Ráckeve -> Közvágóhíd',
            config: {
                stopId: 'BKK_007947',  // Ráckeve
                routeId: 'BKK_H6',
            }



De mivel en jaratlan vagyok e teren igy az altalad irtak alapjan probaltam mukodesre birni.

Koszonom az idod es az eneregiad!

**Comment by unixgirl** [comment]
.

**Comment by balassy** [comment]
Fura, nem értem, hogy az miért okozott gondot, talán valahol elcsúsztak a zárójelek. Mindegy is, a lényeg, hogy megoldódott. Köszi a visszajelzést!
