### ISSUE TITLE
nem frissulo  menetrend

### ISSUE THREAD

**Issue by unixgirl** [balassy/MMM-Futar#29]
Sziasztok, ma reggelre megallt a futar. pontosabban este 22 ora korul mert onnantol nem ad menterendet.
a terminalba nem mutat hibat. leallitottam a tukrot, es ujrainditottam az alkalmazast. 
annyi valtozas tortent, hogy a busz menetrend megjelent viszont a hev menetrend az mar nem, azt irja "menetrend betoltese" de orakig semmi.
majd a gepet is ujrainditottam, de ekkor sem tortent valtozas, a hev menterend nem jelenik meg.
a mirror egy teljesen uptodate rendszerre lett felrakva, ami mukodott is a mai napig, a gepen nem tortentek frissitesek, telepitesek. a tobbi modul az mukodik es mukodott is. volna valami otlet hogy mi a hiba?

**Comment by balassy** [comment]
Szia @unixgirl,

Ha a gépen egy terminal ablakban kiadsz egy `pm2 logs` parancsot, akkor látsz valamilyen hibaüzenetet? Vagy ha böngészőben megnyitod a mirror oldalát (pl. `http://IP-cím:8080/`) egy másik gépről a hálózatban és a böngőszőben nyitsz egy Developer Console-t (F12-vel), akkor ott megjelenik valamilyen hibaüzenet?

**Comment by rvargar** [comment]
Szia @balassy ,

A szóban forgó probléma a hév menetrenddel kapcsolatban nálam is egy ideje fennáll (buszmenetrend helyesen frissül és jelenik meg egy többes megálló esetén). A log a következő hibát tartalmazza:
![image](https://user-images.githubusercontent.com/12526998/216760951-3f2bb20e-31fa-4df6-8bcb-8bc9e856cd31.png)
Egy észrevétel, a hév stop id-kkal kapcsolatban,hogy a stop-idk formátuma eltérő a vonalon:
![image](https://user-images.githubusercontent.com/12526998/216762399-561c1f75-64d8-4598-9901-855ccdeec050.png)
![image](https://user-images.githubusercontent.com/12526998/216762429-a7016d7d-caae-4922-bf79-65da7a4f2529.png)
Kipróbáltam a kétfajta stop_id-t ,de sajnos mind a kettőnél eredménytelen a lekérés.
Köszönöm, hogy ránézel a hibára

**Comment by rvargar** [comment]
Időközben sikerült a config fájlban megfelelő stop_id megadni (Lekérés eredménye már nem null). A hévek id-ja megváltozott, nem tartalmazza a kezdő 'F' karaktert, és több számjegyből áll mint:
https://go.bkk.hu/stop/BKK_09019191
A megállóhoz tartozó irányok sajnos nem különülnek el valamiért. Próbáltam egyel kisebb stop id-val is de ugyanazokat az értékeket adja vissza a query.
https://go.bkk.hu/stop/BKK_09019190 

Köszönöm, hogy megosztod a projektedet.

**Comment by balassy** [comment]
Ezekkel az értékekkel megjelennek nekem az indulási időpontok a megállóból:
```
        {
            module: "MMM-Futar",
            position: "top_left",
            header: 'Margit hídtól indul',
            config: {
                stopId: 'BKK_09019190',  // Margit híd
                routeId: 'BKK_H5',
            }
        },
```

Viszont az irányokkal tényleg gond van. A jelek szerint a hév rendhagyóan viselkedik, a Futár oldalánis egyszerre jelenik meg az összes irány és végállomás, és ahogy látom adatbázis szinten sincsenek megkülönböztetve, mindkét irányban csak `BKK_H5` van megadva `routeId`-ként.

Ami még fura, hogy a `BKK_09019190` és a `BKK_09019191` `stopId` is ugyanarra a megállóra mutat, a `code` tulajdonságok is ugyanaz. Sajnos mindkettőhöz ugyanúgy a közös `routeId` van rendelve.

Egyelőre nincs ötletem, hogyan lenne érdemes finomítani a megoldáson. Ha nektek van, ne habozzatok megosztani velem.

**Comment by radokristof** [comment]
@balassy 
Azt hiszem megint nem megy az API, de most más okból. Úgy tűnik az már nem igaz hogy nem kell API kulcs hozzá.

Ha a README-ben szereplő teszt URL-t megnyitom, ezt kapom:
```
Invalid API key. Please register at https://opendata.bkk.hu
```

**Comment by radokristof** [comment]
https://github.com/balassy/MMM-Futar/pull/31

Nekem így működik most.

**Comment by nygma2004** [comment]
> #31
> 
> Nekem így működik most.

Szia, próbáltam a te forkodat letölteni és telepíteni, de én így is UnhandledPromiseRejection-t kapok. API key megvan, és hozzá is adtam a config-js-hez.

**Comment by balassy** [comment]
Szia! Mergeltem @radokristof branchét (köszönet érte!), így most már a modul támogatja az API kulcsot a kötelező `apiKey` paraméteren keresztül. Remélem ez megoldja a problémát nálad is.
