### ISSUE TITLE
Request/Improvement Idea: Color icons

### ISSUE THREAD

**Issue by zttk** [balassy/MMM-Futar#3]
I was wondering if we could add colored option into the config file. I'm completly new to this project but I may give it a try when I have some free time. I will report back here.

**Comment by zttk** [comment]
It was really easy, I just updated the MMM-Futar.css file for the MMM-Futar .symbol attribute.

I added color: #3699df; and now my BUS icons are blue.

There are still two portions missing:
- Make this icon yellow for TRAM, but that would require creating a different symbol and code change depending on the RouteType value.
- Make these colored icons optional in the config file (I have no idea how to do that).

**Comment by balassy** [comment]
@zttk Tamás, it is a great idea, thanks for submitting! Do you want to color only the vehicle icon, right?
I'll eventually investigate how could I do that in the most flexible way.

**Comment by zttk** [comment]
Yes I think it would be great if the icons would be optionally colored. Like in the standard weather forecast app. It is an option in the config file. If I set colored: true the numbers are colored. 

I imagined this solution similar, only a simple config line: colored True/false. If colored the BUS would be blue and the TRAM would be yellow. If false everything remains as it is. I don't think the user should specify the colors themself (while this may be feasible, I have my calendar entries colored where I selected the colors myself), you should just go with the standard BKK colors, blue for BUS and yellow for TRAM in my opinion (only the icon).

**Comment by balassy** [comment]
@zttk Tamás, I'm happy to announce that I just released version `1.2.0` of the `MMM-Futar` module which displays the symbols and the route text colored by default. You can override the default behavior with the new `colorSymbolInHead`, `coloredTextInHead`, `coloredSymbolInStopTime` configuration flags, and even change the default colors using the `symbolColors` setting.

I hope you like it!

**Comment by balassy** [comment]
Released with version `1.2.0`: https://github.com/balassy/MMM-Futar/releases/tag/1.2.0
