### ISSUE TITLE
Multiple stops in a single module (Egy modul alatt több megálló)

### ISSUE THREAD

**Issue by zoldev** [balassy/MMM-Futar#4]
Tisztelt György Balássy!

Először is köszönöm a munkádat. Nagyon tetszik az alkalmazás!

Szeretnék egy kis segítséget kérni a config beállításához.
Az alább linkelt képen látható formátumhoz hasonlóan szeretnék megjeleníteni két vagy több megállóból induló járatokat, indulási sorrendben, egyetlen egy modul alatt.
https://github.com/balassy/MMM-Futar/blob/master/doc/screenshot-multiple-routes.png
Pl: Orczy tér 9-es busz 83-as troli és a téren közlekedő villamosok indulását is szeretném egy modul alatt látni.
Van erre lehetőség a modulban?

Válaszodat, segítségedet előre is köszönöm!
Üdv: Zoltán

**Comment by balassy** [comment]
Kedves Zoltán,
Jelenleg ez a modul arra képes, hogy egy megálló valamennyi vagy összes járatát mutassa. Arra jelenleg nincs felkészítve, hogy több megállót, vagy egy megálló néhány járatát jelenítse meg. Viszont felteheted a modult több példányban a MagicMirrorra, és mindegyiknél beállíthatsz másik megállót és járatot.
üdv,
György

Dear Zoltán,
Currently this modul is able to display one or more routes from a single stop. At the moment it cannot display more stops, or more some routes from a single stop. As a workaround, you can add the module multiple times to your MagicMirror, and configure different stops and routes for the modules.
Hope this helps,
György

**Comment by zoldev** [comment]
Kedves György!

Köszönöm a válaszodat.
Egy észrevételem lenne:
A trolibusz ikonja nem látszik, hiába van engedélyezve a config-ba.
Illetve még egy kérdés:
Azt be lehet-e állítani egy adott megállóba érkező buszoknál, hogy azokat ne listázza ki ami kevesebb mint 5 perc múlva fog indulni (mondván azt már úgy sem érem el)? Egyszerre 3 elemet jelenítek meg egy modulban és percenként frissíti a listát. 5 perc múlva induló busz, a frissítés után már ne legyen kilistázva, az utána lévők feljebb kerülnek.
Van esetleg erre valami beállítási lehetőség?

Elnézésedet kérem, ha buta kérdéseket teszek fel, nem értek a programozáshoz. :(

Üdv,
Zoltán

**Comment by balassy** [comment]
Kedves Zoltán!
A troli ikonnak meg kellene jelennie, ha mégsem teszi, akkor ez valószínűleg egy hiba. Ki fogom nyomozni, feltettem rá egy önálló issue-t: #5 .
Jelenleg nincs olyan opció, hogy a túl korán induló járatokat ne listázza a modul. Ez jó ötlet, de fejlesztést igényel, ennek a követésére is felvettem egy önálló issue-t: #6.
üdv,
György

Dear Zoltán,
If the trolleybus icon is not displayed properly, than it is a bug. I'll investigate and fix it, and created a separate issue to track it: #5.
Currently there is no option to filter out too early stop time. It is good idea, I created a separate issue to track this feature request: #6.
Cheers,
György

**Comment by zoldev** [comment]
Kedves György!

Előre is köszönöm a további fejlesztésekbe, hibajavításba fektetett munkádat.

Szép napot!
Zoltán

**Comment by balassy** [comment]
Kedves Zoltán!
Köszönöm,  hogy jelezted a troli ikon problémát, kijavítottam a kódot, az 1.3.1 verzióban már helyesen kell megjelennie az ikonoknak. Ha mégsem, kérlek vegyél fel újabb issue-t itt a Githubon.
Üdv,
György

Dear Zoltán,
Thank you for reporting the icon issue. I've fixed the bug and released version [1.3.1](https://github.com/balassy/MMM-Futar/releases/tag/1.3.1) which should render trolleybus icons correctly.
If you experience any other problems, feel free to create additional issue tickets here.
Hope this helps,
György

**Comment by balassy** [comment]
Kedves Zoltán!
Az imént tettem elérhetővé az [1.4.0 verziót](https://github.com/balassy/MMM-Futar/releases/tag/1.4.0), amiben megjelent egy új `hideStopTimesInNextMinutes` beállítás, amivel kiszűrhetőek a túl korai indulások. Ha ez így valamiért nem megfelelő, kérlek vegyél fel a problémára újabb issue-t itt a Githubon.
üdv,
György

Dear Zoltán,
I'm happy to announce that I've just released [version 1.4.0](https://github.com/balassy/MMM-Futar/releases/tag/1.4.0) which includes a new `hideStopTimesInNextMinutes` configuration option which allows filtering out too early departure times.
Hope this helps,
György
