### ISSUE TITLE
Trolleybus icon is not displayed

### ISSUE THREAD

**Issue by balassy** [balassy/MMM-Futar#5]
According to issue #4 the trolleybus icon is not displayed correctly in the module.

**Comment by balassy** [comment]
Thank you for reporting this issue. I've fixed the bug and released version [1.3.1](https://github.com/balassy/MMM-Futar/releases/tag/1.3.1) which should render trolleybus icons correctly.

If you experience any other problems, feel free to create additional issue tickets here.

**Comment by balassy** [comment]
This is how it looks like after the bug fix:

![trolleybus-icon-fixed](https://user-images.githubusercontent.com/1872777/51692160-a14e6580-1ffc-11e9-8e36-98255646dc2b.png)

**Comment by GattoJohnny** [comment]
Szia! Most frissítettem 1.4.0-ra, és még mindig nem jó az ikon. Regresszió?
![trolley-natgeo](https://user-images.githubusercontent.com/47010649/51706102-bbe50680-201d-11e9-82b4-c875cd0124c6.jpg)
Üdv, Gyuri

**Comment by balassy** [comment]
A MagicMirrornak melyik verziója fut nálad?

**Comment by GattoJohnny** [comment]
Azt is ma frissítettem. 2.6.0.

**Comment by balassy** [comment]
A MagicMirror frissítése után futtattál `npm install`-t is és újraindítottad az egész alkalmazást?

**Comment by GattoJohnny** [comment]
Panaszkodik a stylelintre, de nem hiszem, hogy az lenne a baj.

"pi@infotukor:~/MagicMirror/modules/MMM-Futar $ git pull && npm install
Already up-to-date.
npm WARN grunt-stylelint@0.10.1 requires a peer of stylelint@^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-recommended@2.1.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN stylelint-config-standard@18.2.0 requires a peer of stylelint@^8.3.0 || ^9.0.0 but none is installed. You must install peer dependencies yourself.

audited 717 packages in 10.125s
found 0 vulnerabilities"

**Comment by GattoJohnny** [comment]
> 
> 
> A MagicMirror frissítése után futtattál `npm install`-t is és újraindítottad az egész alkalmazást?

Az egész oprendszert újraindítottam...

**Comment by balassy** [comment]
A stylelint nem probléma.
Arra gondoltam, hogy miután a MagicMirrort frissítetted, akkor az egész alkalmazásra is indítottál `npm install`t?

**Comment by GattoJohnny** [comment]
> 
> 
> A stylelint nem probléma.
> Arra gondoltam, hogy miután a MagicMirrort frissítetted, akkor az egész alkalmazásra is indítottál `npm install`t?

Nem tudom, hogy a MagicMirror keretrendszert vagy a Futárt érted-e egész alkalmazás alatt. Ez történt:

cd MagicMirror
git pull && npm install
cd modules/MMM-Futar
git pull && npm install
(Itt volt egy kis közjáték, mert korábban beleírtam a MMM-Futar.js-be, de miután git reset --hard-oltam, ment.)
gép újraindítása
piros NatGeós ikon.

**Comment by zoldev** [comment]
Sziasztok!
Nekem is piros NatGeos ikon jelenik meg.
Mondjuk a MagicMirror-t nem frissítettem csak a modult.
(Viszont a hideStopTimesInNextMinutes remekül működik! Ezer köszönet :D )

**Comment by zoldev** [comment]
Megtörtént a MM update is és azután sem jelenik meg.
A 'header'-ben sem.

**Comment by balassy** [comment]
A troli ikon (`fa-bus-alt`) csak a FontAwesome ikon csomag v5 verziójától érhető el, ami a MagicMirror 2.6.0 verzióval jelent meg. 

A `vendor\node_modules\@fortawesome\fontawesome-free` mappában lévő `package.json` fájlban a `version` property értéke mennyi? Én a `develop` branchen vagyok és nálam ez a property a 83. sorban van és az értéke `5.6.3`.

**Comment by GattoJohnny** [comment]
5.6.3

**Comment by balassy** [comment]
Hm, nem sikerül reprodukálnom, csak tippelni tudok.

Az `MMM-Futar.js` fájl 49. sorában van az alábbi függvény:
```JavaScript
  getStyles() {
    return [
      'MMM-Futar.css',
      'font-awesome.css'
    ];
  },
```
Valaki ki tudná próbálni, hogy kiegészíti egy sorral az alábbiak szerint:
```JavaScript
  getStyles() {
    return [
      'MMM-Futar.css',
      'font-awesome.css',
      'font-awesome5.css'
    ];
  },
```
A `font-awesome5.css` sor került be, plusz az előző sor végére egy vessző.
Így a mirror újraindítása után megjelenik a troli ikon?

**Comment by GattoJohnny** [comment]
Sajnos a font-awesome5.css-sel sem jó.

**Comment by GattoJohnny** [comment]
Hahó! Ezt a font-awesome5.css ötletet ne hagyjuk ennyiben! Lehet, hogy nálad más a konfig.
Nálam a MagicMirror/vendor/node_modules/font-awesome/css mappában van "font-awesome.css", de nincs "font-awesome5.css". Nem látok a kódban olyan hivatkozást, ami a netről töltené a fájlt, szóval úgy tippelem, hogy ott kéne lennie valahol a gépemen.

**Comment by GattoJohnny** [comment]
Letöltöttem a https://fontawesome.com/download oldalról az 5.6.3-as változatot (free for web), a zip-ben lévő fontawesome.css-t font-awesome5.css-re átnevezve betettem az MMM-Futar könyvtárba, az MMM-Futar.css mellé, újraindítottam a tükröt, de ez sem segített.

Nem lehet, hogy a nyelvi beállításokkal függ össze? Nálam magyarra van állítva a Raspbian. Meg a tükör is.

**Comment by GattoJohnny** [comment]
További adalék a nyomozáshoz. Alighanem valami általános hibáról lehet szó, mert a rendszer alapértelmezett Current Weather moduljának szélirány ikonja is megfeküdt. Pedig korábban jó volt. Nem tudom időponthoz kötni a hibát, de nincs kizárva, hogy a 2.6.0 frissítés tett be neki.
![currentweather-natgeo](https://user-images.githubusercontent.com/47010649/51758956-564d5480-20c7-11e9-8f88-047af99a25ef.jpg)

**Comment by balassy** [comment]
Hm, ez érdekes. Olyan, mintha a frissítés nem futott volna le teljesen. Megpróbálnád, hogy futtatsz egy `npm install`-t a `vendor` mappában?

**Comment by zoldev** [comment]
Sziasztok!
Nekem se látszik a Current Weather moduljának szélirány ikonja.
Lefuttattam egy `npm install`-t a `vendor` mappában aztán újraindítottam a tükröt, de továbbra sem oldotta meg a problémát... :(

**Comment by GattoJohnny** [comment]
Nálam sem javult meg. 
Aztán átállítottam a tükör nyelvét angolra, maradt a hiba. 
Átállítottam a Raspberry-t angolra, maradt a hiba. 
Vissza fogok állni lemezképből 2.5.0-ra, a Futárt frissítem, és megnézem az eredményt.

**Comment by balassy** [comment]
Erről a szélirány ikonról beszélünk?

![current-weather-icon](https://user-images.githubusercontent.com/1872777/51878037-8e29f580-236e-11e9-9042-2ba201a85d0e.png)

Most megnéztem a Current Weather modul kódját, és az 7 hónapja nem változott, ráadásul a szélirány nem is képként, hanem szövegként van kiírva, ezért is tud lokalizálva megjelenni:

![current-weather-markup](https://user-images.githubusercontent.com/1872777/51878067-ac8ff100-236e-11e9-87d2-84f012f02c7d.png)

Szóval kicsit nagyobbnak tűnik a probléma, mint hogy a troli ikon nem jelenik meg. Minden más működik rendesen?

**Comment by GattoJohnny** [comment]
Igen, erről a karakterről van szó. Két paraméter befolyásolja a megjelenését.
- showWindDirection (Default value: true)
- showWindDirectionAsArrow (Default value: false)

Szövegesen működik 2.5.0-ban és 2.6.0-ban egyaránt. 
Nyilasan megy 2.5.0-ban, de nem megy a 2.6.0-ban.

Arra gondoltam, én rontottam el valamit telepítéskor. Ezért:
- leformáztam a kártyát
- csináltam egy szűz installt, kezdve a legújabb Raspbiantól (NOOBS 3.0.0, amiben asszem 4.14-es kernel van)
- magyar nyelv, magyar billentyűzet kiválasztva
- MagicMirror 2.6.0 
- showWindDirectionAsArrow: true beállítása (meg persze appid és locationID) a konfigban.

Már ennyitől elromlott a nyíl. Tervezem megint újrahúzni, de maradva az alapértelmezett angol nyelvnél. (Igen, utólag is át lehet állítani az oprendszeren és a tükrön is, de biztos ami biztos.) Nem fűzök hozzá sok reményt.

Az éles rendszeren egyébként visszaálltam 2.5.0-ra ill. 1.4.0-ra, elfogadva, hogy a troli rosszul jelenne meg (ha állítanék be ilyet). Nem hiszem, hogy a fejlesztők időt szánnának a hibakeresésre, mert 
1) a képernyőfotók nagy részén az látszik, hogy az emberek szövegesen használják, tehát nem is szembesülnek a hibával
2) úgy látom, inkább az új, hibrid modulra koncentrálnak, amire a Current Weathert és a Weather Forecastot tervezik lecserélni.

Minden más működik rendesen. Köszi az eddigi nyomozást és még nagyobb főhajtás a Futár modul előtt.

**Comment by radokristof** [comment]
Nekem teljesen más config, egyelőre még készítés alatt áll a kész tükör, ezért vm-ben futattom Debian-on a MagicMirrort (manual install méghozzá, mivel ugye a RPi-s script nem megy) és ugyanez a hiba. Nem jelenik meg a nyilacska a széliránynál.
Szerintem is ez már lassan le fog kerülni a tükörről és az új modul veszi át a helyét (ami egyelőre nekem még annyira nem akar jól működni).

**Comment by balassy** [comment]
Szerintem érdemes lenne akár a fórumban rákérdeznetek, akár egy Github Issue-t nyitni az ikonnal kapcsolatban, mert bár elsőre úgy tűnhet, hogy csak a beépített időjárás modullal van probléma, de valójában valami annyira nem stimmel, hogy más modulokat is megzavar.

**Comment by radokristof** [comment]
Lehet nyitni fogok egyet. Kicsit off kérdés, de részben ehhez a témához tartozik. Nektek az ő,ű karakter rendesen jelenik meg? Nekem valami default font-al jelenik meg (kb Arial vagy nem tudom mi az alap Raspbian-on). Most telepítettem frissen egy RPi-re de VM-ben is ugyanilyen volt. Minden más, tökéletes, egyedül ezek a karakterek olyanok mintha nem lenne benne a fontkészletben. (á, é pl okés).

**Comment by GattoJohnny** [comment]
Az alapértelmezett Roboto Condensed betűkészletben van Latin-2 támogatás, tehát gond nélkül kéne jönnie az ő-nek és ű-nek is. Nálam működik. A 1100-s hibajegyben (https://github.com/MichMich/MagicMirror/issues/1100) erről diskurálnak. A párbeszéd végén valaki megemlíti, hogy ha Raspbian Lite verziót telepítettél, akkor kezdd elölről a full Raspbiannal.

**Comment by GattoJohnny** [comment]
Gyuri, már kerestem a fórumban az ikonos problémára, de csak szőr mentén. Mindjárt nekilátok rendesen áttúrni. De azt a jelenlegi ismereteim birtokában nem merném megkockáztatni, hogy összefüggésbe hozzam a troli ikon elromlásával, és ezt leírjam. Talán így van, de nem tudom nekik bizonyítani. 
Attól tartok, hogy visszakérdeznek, európai-e vagy afrikai, én meg repülök a szakadékba...

**Comment by radokristof** [comment]
Full Raspbian van a recommended softwares nélkül.  Nem a condensed az alapértelmezett, vagy rosszul tudom? A ticketben látszólag masok a betűk mint nekem. Az a fura hogy nem csak Raspiannal volt ilyen hanem sima Debiannal is.

**Comment by GattoJohnny** [comment]
>  Nem a condensed az alapértelmezett,

Nálam 2.5.0 fut. A main.css-ben ez szerepel:
body {
  margin: 60px;
  ...
  font-family: "Roboto Condensed", sans-serif; 

Tehát a Roboto Condensed az alapértelmezett. Nem tudom, nálad miért nem az. Utoljára két éve, a 2.1.3-ban babráltak a fontokkal, azóta ezt (és így, npm install-lal) használják. A mostani 2.6.0-ban is megtartották.

**Comment by GattoJohnny** [comment]
Még nem tudom, mi okozza, hogy nálunk nem, nálad viszont jól jelenik meg az ikon. Viszont néhány további adalékkal tudok szolgálni. Telepítési lépések és eredmények alább.


1) Pőre MM 2.6 (automatikus indulás, egérelrejtés, képernyővédő-tiltás, modulok stb. NÉLKÜL)

1.1 MM2 v2.6 telepítése 
1.2 szélirány ikon megjelenik
1.3 MMM-Futar 1.4.0: cd modules, git clone https://github.com/balassy/MMM-Futar.git
1.4 szélirány ikon elromlott, troli helyett NatGeo
1.5 cd MMM-Futar, npm install
1.6 ikonok nem javultak meg


2) Arra gondoltam, hogy talán az npm-et kéne frissíteni, de az sem segített:

2.1 MM2 v2.6 telepítése 
2.2 szélirány ikon megjelenik
2.3 npm 5.6.0 → 6.9.0: sudo npm i -g npm
2.4 MMM-Futar 1.4.0: cd modules, git clone https://github.com/balassy/MMM-Futar.git
2.5 szélirány ikon elromlott, troli helyett NatGeo
2.6 cd MMM-Futar, npm install
2.7 ikonok nem javultak meg


3) Aztán teljesen kihagytam az npm-et. Ez lett a legérdekesebb:

3.1 MM2 v2.6 telepítése 
3.2 szélirány ikon megjelenik
3.3 másik telepítésben tar-ral összecsomagolt archívum kibontása a kézzel létrehozott MMM-Futar könyvtárba
3.4 szélirány ikon elromlott, troli helyett NatGeo
3.5 MMM-Futar könyvtár törlése
3.6 szélirány ikon megjavult!


Ebből tudsz valamire következtetni?

**Comment by radokristof** [comment]
Köszi először is a segítséget, megnéztem nekem is az a font van mint neked, mégis problémáin vannak még mindig az ő,ű betűkkel. 
Az ikon ugyanígy nem megy nekem. Ha viszont csak a modul klónozással után romlik el, lehetséges hogy valamit felülír a modul?

**Comment by GattoJohnny** [comment]
Az ékezetes problémával kapcsolatban nincs több ötletem, de talán nem is ez a megfelelő fórum téma hozzá. Érdemes lenne a https://forum.magicmirror.builders/ -en belül nyitni rá egy újat.

Ami a második felvetésedet illeti, ebben Balássy Gy. az illetékes. Várjuk a véleményét.

**Comment by radokristof** [comment]
Igazad van, nem is akarom spammelni ezt az issue-t ezzel. Azért írtam be ide, mert gondoltam hogy lehet ehhez köze. Ugyanis írtam a fórumra is, de ott se kaptam valós megoldást, illetve korábbiak között se találtam megoldást. Mind1 köszi, várjuk ennek az ikon problémának a megoldását. Kipróbáltam hasonlóan mint te, újrarakni, hasonló eredmény született.

**Comment by balassy** [comment]
Pontosan hol nem jelennek meg jól a magyar ékezetes betűk?

Most beállítottam úgy a mirrort, hogy csak a `currentweather` modul legyen rajta és `showWindDirectionAsArrow: true`. Nem jelenik meg a szélirány ikon. Ha kiteszem még az `alert` modult is, akkor viszont már megjelenik jól, tehát hatnak egymásra a modulok. Következő körben kitettem rá a Futár modult is, a szélirány még mindig jó, és a Futár modul `header`-jébe írt magyar ékezetek is megjelennek, a troli ikon is rendben. Ezt egyelőre desktop Windowson próbáltam, nem RPi-n.

Az aggaszt, amit @GattoJohnny írt, hogy a Futár modul telepítése után más elromlik, de még nem tudom az okát.

**Comment by balassy** [comment]
Teszteltem pár csillagállást RPi-n is, minden más modul nélkül:
- Futár modul önmagában jó (troli ikon van, ékezetek a `header`-ben megjelennek).
- CurrentWeather modul önmagában nem jó (nincs szélirány ikon).
- CurrentWeather + Alert jó (van szélirány ikon)
- CurrentWeather + Futár jó (van szélirány ikon)

**Comment by GattoJohnny** [comment]
Misztikus. Arra azért kíváncsi vagyok, úgy tetted-e fel a Futárt, mint bármely más földi halandó (git clone..., nem bejelentkezve), vagy úgy, mint akinek otthon a fiókban épp van belőle egy fejlesztés alatt álló változata?

;-)

**Comment by GattoJohnny** [comment]
Leteszteltem ugyanezeket a konfigokat. Részben más eredményt kaptam. Még akkor is, ha eltekintek attól, hogy nálam még sosem jelent meg a troli ikon. Két állapot van: vagy piros téglalap, vagy semmi. Alighanem a "semmi" felel meg annak az állapotnak, amikor nálad megjelenik.

- Futár modul önmagában jó (igaz, hogy troli ikon nincs, de legalább nem NatGeo, ékezetek a header-ben megjelennek).
- CurrentWeather modul önmagában nem jó (nincs szélirány ikon).
- CurrentWeather  + Alert nem jó (nincs szélirány ikon).
- CurrentWeather + Futár jó (van szélirány ikon).

Viszont! Hozzáadva a "calendar" modult, ami használ szimbólumot, elromlik a szélirány és a troli is. Nem eltűnnek, hanem téglalap jelenik meg helyettük.

**Comment by GattoJohnny** [comment]
Mutatok még cifrát. 

	language: "hu",
	timeFormat: 24,
	units: "metric",

beállítások mellett

- Futár modul + clock és/vagy currentweather modul: magyar szöveg (fejlécben ékezetek helyesen)

![Futar+clock](https://user-images.githubusercontent.com/47010649/54199875-3aacda80-44ca-11e9-8c2b-af12201d4370.jpg)

- Futár modul egymagában: angol szöveg (fejlécben ékezetek helyesen)

![Futar_alone](https://user-images.githubusercontent.com/47010649/54199926-587a3f80-44ca-11e9-927e-9e61b823ab76.jpg)

**Comment by GattoJohnny** [comment]
Visszatérve az eredeti felvetésre (a troli ikonra).

Nem tudom, ez segít-e. Megvizsgáltam a troli ikon helyét és a busz ikont a Chrome fejlesztői eszközével (Ctrl-Shift-I). A két kódrészletet összehasonlítva azt találtam, hogy hiányzik ez a darabka a trolisból:

![Futar_Ctrl-Shift-I_Pseudo](https://user-images.githubusercontent.com/47010649/54206704-1dcbd380-44d9-11e9-99cd-6bf9ed4bc366.jpg)

**Comment by balassy** [comment]
A busz az `fa-bus`, a troli pedig az `fa-bus-alt` ikon a FontAwesome gyűjteményből, a Futár modul kódjában csak ennyi a különbség közöttük.
Az általad bemásolt beállítás a FontAwesome-ból jön, és ott azt látom, hogy megvan ugyanez mindkét ikonhoz:

![fa-bus](https://user-images.githubusercontent.com/1872777/54246793-a62c9180-4536-11e9-8687-9ef3e3e213f2.png)

A `content` tulajdonság értéke azért tér el, mert az reprezentálja az ikon rajzolatát.

**Comment by balassy** [comment]
Köszi a választ, és hogy tesztelted a különböző konfigokat. 
Az tényleg cifra, hogy az egyik sorban megjelenik a busz ikon, a következőben pedig nem. Erre elképzelésem sincs, hogy mi okozhatja...
A `calendar_monthly`+`current_weather`+Futár modul hármassal nekem jók az ékezetek és megjelenik a szélirány ikon is.
Igen, RPi-re git clone-nal tettem fel a modult, de hamarosan kipróbálom egy másik szűz környezeten is.

**Comment by GattoJohnny** [comment]
Elnézést az elégtelen leírásért, és azért, ha ezzel fölösleges köröket futottál. A busz-semmi-semmi-busz ikonok váltakozása történetesen rendben van, mert abban a megállóban megáll a busz és a troli is. (Nem adtam meg routeId-t.) A semmi a trolit jelenti. 
Abban a hozzászólásban a nyelv megváltozására hívtam föl a figyelmet. (Nem próbáltam ki más modullal, de valószínűsítem, hogy nem Futár-specifikus a probléma.)

**Comment by balassy** [comment]
Telepítettem a mirrort és a Futár modult egy szűz MacBookra, és mind az ékezetek, mind a szélirány ikon, mind pedig a troli ikon rendben van. Egyedül a szélirány ikonnal volt annyi probléma, hogy az a modul önmagában nem jelent meg helyesen, de ha kitettem az alert vagy a clock modult, akkor már megjelent a szélirány ikon is.

**Comment by GattoJohnny** [comment]
Emelem kalapom az egyéb platformok előtt. Nálam csak RPi-n fut, de még azon az egyen sem tudom előcsalni a fránya troli ikonokat. Noobs-ról átálltam "Raspbian Stretch with desktop and recommended software" telepítőre, 2.6-os MM-et húztam rá, git pull-lal Futár, csak Futár modul bekapcsol (Current Weathert bottal sem piszkáltam), és nincsenek trolik.

Itt feladom, várok további verziókat. Az idő minden sebet begyógyít egyszer...
Még mindig jobb a helyzet, mintha se ikonjaim, se ékezeteim nem lennének.    :-)

**Comment by GattoJohnny** [comment]
@radokristof : időközben rájöttem, hogy nálam is kompromisszumosan jelentek meg az ékezetek. Volt ugyan hosszú ő meg ű, de másik betűtípusból (vagy másik változatból). A MM alapértelmezett betűje a Roboto Condensed. Nem tudom ellenőrizni, de elképzelhető, hogy ebből hiányoznak a Latin-2-es karakterek, s helyette mondjuk Roboto Regularból pótolja, vagy valami másból.
Nem is kísérleteztem a megpatkolásával, választottam egy nagyon hasonló betűt, ami teljes karaktertámogatással bír: lecseréltem a custom.css-ben a Roboto-t **Piboto**-ra. RPi-n biztos ott van helyből, de valahol azt olvastam, hogy Debianon is megvan. Ráadásul léteznek azok a változatai, amik a main.css-ben szerepelnek (thin, light, regular stb.). Nincs kizárva, hogy Michael ebből indult ki, de még egyedibbé akarta tenni a kinézetet, vagy csak azt akarta, hogy más platformokra is hordozható legyen.
Játszani kell kicsit a css-sel, hogy kikísérletezd, melyik tetszik neked a legjobban. Én így állítottam be az enyémet:

body {
  ...
  font-family: "Piboto Light", sans-serif;
}

.thin {
  font-family: Piboto, sans-serif;
}

.light {
  font-family: "Piboto Light", sans-serif;
}

.regular {
  font-family: "Piboto Light", sans-serif;
}

.bold {
  font-family: "Piboto Light", sans-serif;
}

header {
  font-family: "Piboto Light", Arial, Helvetica, sans-serif;
}

**Comment by radokristof** [comment]
@GattoJohnny Köszi, ezt ki fogom próbálni! Ez akkor raspbian-ban benne is van alapból? Kipróbálom a te configodat... 
Amúgy én is próbáltam rájönni erre, én arra jutottam, hogy csak a newsfeed modulban jelenik meg ilyen bénán (igen rosszul fogalmaztam, nem az, hogy nincs ő, ű - van csak más font-al helyettesíti). Itt a posztom a [fórumon](https://forum.magicmirror.builders/topic/10077/special-characters-won-t-appear-correctly-on-newsfeed-module) erről, ott van screenshot is. Calendarban pl jól megjelenik ebben a fontban is az ő és ű.

**Comment by radokristof** [comment]
Köszi, ezzel a beállítással nekem is minden szépen jelenik meg! Igaz a Roboto egy fokkal jobban tetszik (vagy csak szokatlan még :) ) de sokkal jobb, hogy végre nincsenek ilyen problémáim, elég hülyén nézett ki...

**Comment by GattoJohnny** [comment]
MM v2.7.1 + MMM-Futar v1.4.0
![NatGeo_MMv2_7+Futarv1_4_0](https://user-images.githubusercontent.com/47010649/58513022-cfa4a300-819e-11e9-98d8-3f0f0939e5c1.jpg)
Meggyógyult. Nem tudom, hol volt benne a bibi, de a verzióváltások meghozták a trolis ikonokat.
Köszönöm a kitartó segítséget.

**Comment by GattoJohnny** [comment]
Ja! És @radokristof ! (Továbbra sem ide tartozki, de ha már itt kezdtük el, érjen is itt véget:)
Nem akarom elkiabálni, de úgy tűnik, működnek az Ő és Ű ékezetei a szebb rajzolatú, alapértelmezett betűtípussal! 😃 
![NatGeo_MMv2_7+Futarv1_4_0-font](https://user-images.githubusercontent.com/47010649/58513530-f7e0d180-819f-11e9-977a-004ad019aedf.jpg)

**Comment by GattoJohnny** [comment]
Kérdés @balassy -hoz, mert megismerhetted a Futár API-ján keresztül a menetrend működését. Csak most vettem észre a két képernyőfotó összehasonlítása után, hogy ugyanaz a troli egyszer 23:26-ra, másszor 23:27-re van kiírva.  Csak kíváncsiságból kérdezem, vajon hogy lehet ez? Számított érték talán, ami kerekítés miatt változhat?

**Comment by radokristof** [comment]
Köszi meg fogom nézni :) De ha jol emlekszem nekem mindig csak a newsfeed modulon volt problema az ekezettel ( vagy neked most sincs ott?) ezert se gondoltam eleinte hogy font problema lehetne...

**Comment by balassy** [comment]
@GattoJohnny A Futár API többféle érkezési időpontot ad meg. Alapvetően a menetrendben szereplő időpontot, de ha van pontosabb információ az adott járműről, akkor azt is visszaadja. A MMM-Futar modul pedig elsődlegesen ez utóbbi, pontosabb adatot használja, ha nincs, akkor viszont a menetrendben szereplőt. A modul percenként frissül, és elképzelhető, hogy közben változik a jármű várható érkezési ideje.

**Comment by balassy** [comment]
Köszönöm a visszajelzéseket, ezek alapján én lezárom ezt az issue-t.
