### ISSUE TITLE
Nothing displayed

### ISSUE THREAD

**Issue by startika22** [balassy/MMM-Futar#8]
I tried this module with a custom config and nothing was displayed, so I tried the sample config provided and that didn't help either. An empty div is created for the module, but nothing in it.
Is it possible that the API changed and there's an error in the parsing? Are there any logs I could take a look at? All other MMM modules I tried worked correctly.

**Comment by startika22** [comment]
I checked a sample API call and a well-formed response with correct bus connections were returned, but nothing shows up in the module.

**Comment by balassy** [comment]
I'm sorry for the inconvenience.
I use this module every day with custom configuration, and it works on my mirror. When you open the DevTools with CTRL+SHIFT+i, do you see any errors on the Console tab?

**Comment by startika22** [comment]
Ok, found the problem. Cloning from git creates the folder name MMM-futar, but the module is searched for in the folder MMM-Futar. And since apache installed with MagicMirror is configured to be case sensitive by default, it didn't find the folder by that name.

**Comment by balassy** [comment]
Thanks for letting us know the solution, and I hope you enjoy using the module!
